#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the transmission-daemon package to those
        # expected by OpenMediaVault.
        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            invoke-rc.d --force transmission-daemon stop
            update-rc.d transmission-daemon disable >/dev/null

            # Restart rsyslog to load the provided configuration. Only needs
            # to be done when the plugin is installed.
            invoke-rc.d rsyslog restart
        fi

        # Update the configuration.
        SERVICE_XPATH_NAME="transmissionbt"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Updating configuration"

            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "pexenabled" "1"
            omv_config_add_element "${SERVICE_XPATH}" "dhtenabled" "1"
            omv_config_add_element "${SERVICE_XPATH}" "lpd-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}" "utp-enabled" "1"
            omv_config_add_element "${SERVICE_XPATH}" "encryption" "1"
            omv_config_add_element "${SERVICE_XPATH}" "message-level" "2"
            omv_config_add_element "${SERVICE_XPATH}" "lazy-bitfield-enabled" "1"
            omv_config_add_element "${SERVICE_XPATH}" "scrape-paused-torrents-enabled" "1"
            omv_config_add_element "${SERVICE_XPATH}" "umask" "18"
            omv_config_add_element "${SERVICE_XPATH}" "cache-size-mb" "4"
            omv_config_add_element "${SERVICE_XPATH}" "rpcport" "9091"
            omv_config_add_element "${SERVICE_XPATH}" "rpcurl" "/transmission/"
            omv_config_add_element "${SERVICE_XPATH}" "rpcauthenticationrequired" "1"
            omv_config_add_element "${SERVICE_XPATH}" "rpcusername" "admin"
            omv_config_add_element "${SERVICE_XPATH}" "rpcpassword" "openmediavault"
            omv_config_add_element "${SERVICE_XPATH}" "blocklistenabled" "0"
            omv_config_add_element "${SERVICE_XPATH}" "blocklistsyncenabled" "0"
            omv_config_add_element "${SERVICE_XPATH}" "blocklistsyncfrequency" "daily"
            omv_config_add_element "${SERVICE_XPATH}" "blocklisturl" "http://www.example.com/blocklist"
            omv_config_add_element "${SERVICE_XPATH}" "script-torrent-done-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}" "script-torrent-done-filename"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules"; then
            omv_config_add_element "${SERVICE_XPATH}" "modules"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/filesandlocations"; then
            omv_config_add_element "${SERVICE_XPATH}/modules" "filesandlocations"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "download.sharedfolderref"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "download-dir"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "incomplete-dir-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "incomplete.sharedfolderref"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "incomplete-dir" "incomplete"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "watch-dir-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "watch.sharedfolderref"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "watch-dir" "watch"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "preallocation" "1"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "rename-partial-files" "1"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "start-added-torrents" "1"
            omv_config_add_element "${SERVICE_XPATH}/modules/filesandlocations" "trash-original-torrent-files" "0"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/bandwidth"; then
            omv_config_add_element "${SERVICE_XPATH}/modules" "bandwidth"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-down" "100"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-down-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-up" "100"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-up-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "upload-slots-per-torrent" "14"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-up" "50"
            omv_config_add_element "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-down" "50"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/queuing"; then
            omv_config_add_element "${SERVICE_XPATH}/modules" "queuing"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "queue-stalled-enabled" "1"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "queue-stalled-minutes" "30"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "download-queue-enabled" "1"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "download-queue-size" "5"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "seed-queue-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/queuing" "seed-queue-size" "10"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/peer"; then
            omv_config_add_element "${SERVICE_XPATH}/modules" "peer"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "bind-address-ipv4" "0.0.0.0"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "bind-address-ipv6" "::"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-limit-global" "240"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-limit-per-torrent" "60"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-socket-tos" "default"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-port" "51413"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-port-random-high" "65535"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-port-random-low" "1024"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "peer-port-random-on-start" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/peer" "port-forwarding-enabled" "1"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/scheduling"; then
            omv_config_add_element "${SERVICE_XPATH}/modules" "scheduling"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-begin" "540"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-end" "1020"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-day" "127"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "idle-seeding-limit" "30"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "idle-seeding-limit-enabled" "0"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "ratio-limit" "2.0"
            omv_config_add_element "${SERVICE_XPATH}/modules/scheduling" "ratio-limit-enabled" "0"
        fi

        # Add Zeroconf configuration.
        ZEROCONF_XPATH="/config/services/zeroconf/services"

        if ! omv_config_exists "${ZEROCONF_XPATH}/service[id='transmissionbt']"; then
            zeroconf=""

            zeroconf="${zeroconf}<id>transmissionbt</id>"
            zeroconf="${zeroconf}<enable>1</enable>"
            zeroconf="${zeroconf}<name>%h - BitTorrent</name>"

            omv_config_add_element "${ZEROCONF_XPATH}" "service" "${zeroconf}" true
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
